<h1>NumPy, The "container" for our data<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#On-array-dimensionality" data-toc-modified-id="On-array-dimensionality-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>On array dimensionality</a></span></li><li><span><a href="#Useful-helper-functions-for-array-generation" data-toc-modified-id="Useful-helper-functions-for-array-generation-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Useful helper functions for array generation</a></span></li><li><span><a href="#Indexing-and-slicing" data-toc-modified-id="Indexing-and-slicing-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Indexing and slicing</a></span></li><li><span><a href="#Exercise-1" data-toc-modified-id="Exercise-1-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Exercise 1</a></span></li><li><span><a href="#Exercise-2" data-toc-modified-id="Exercise-2-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Exercise 2</a></span></li><li><span><a href="#Exercise-3" data-toc-modified-id="Exercise-3-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Exercise 3</a></span></li><li><span><a href="#Shallow-vs.-Deep-Copy" data-toc-modified-id="Shallow-vs.-Deep-Copy-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Shallow vs. Deep Copy</a></span></li></ul></div>

The evaluation of scientific data, i.e. measurement data, is almost always about the evaluation of **numbers**. This applies, e.g., to LFP time series, patch-clamb recordings or multi-fluorescence images. 

The mathematical functions of pure _Python_ are limited. Anything beyond basic operations (+, -, /, \*) has to be programmed by ourselves.  We can of course do that - or: We use one of the many packages where others have already done the work for us. Such a useful package is **NumPy** ([numpy.org/doc/stable/](https://numpy.org/doc/stable/)).

<figure class="image">
  <img src="img/NumPy.png" alt="NumPy Logo" style="width: 50%;">
  <figcaption>image source: <a href="https://commons.wikimedia.org/wiki/File:NumPy_logo_2020.svg">commons.wikimedia.org</a>, license: <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">CC BY-SA 4.0</a></figcaption>
</figure>

## Introduction
Let's have a first look:

In [1]:
import numpy as np

# let's create our first NumPy-array:
array_1 = np.arange(10) # = np.arange(0,10,1)
array_2 = np.array([1, 2, 3])

print(f"array_1: {array_1}")
print(f"array_2: {array_2}")

array_1: [0 1 2 3 4 5 6 7 8 9]
array_2: [1 2 3]


In [2]:
print(type([1, 2, 3]))
print(type(array_2))

<class 'list'>
<class 'numpy.ndarray'>


The `import` command makes all functions within the _NumPy_ package available for our own program. These functions can be called by `np.FUNCTION(...)`, e.g. `np.mean(array_1)`:

In [3]:
print(f"np.mean(array_1): {np.mean(array_1)}")

np.mean(array_1): 4.5


The `np.arange(start,stop,step)` command creates a so-called _NumPy_ array similar to the `range` command, but with the advantage that we can directly access the array (to achieve the same with the `range` command: `list(range(10))`). And we now can create arrays with floating point numbers:

In [8]:
array_3 = np.arange(0, 5, 0.5)
print(f"array_3: {array_3}")

array_3: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


The `np.array([1, 2, 3])` command converts any given list (or other array-like object) into a _NumPy_ array. 

One main advantage of a _NumPy_ array is, that one can directly call basic _NumPy_ functions via `array.mean()` instead of `np.mean(array)` (while both is valid):

In [9]:
print(f"array_1.mean(): {array_3.mean()}")

array_1.mean(): 2.25


Some further examples:

In [10]:
print(f"array_1.std(): {array_1.std()}")
print(f"array_1.max(): {array_1.max()}")
print(f"array_1.min(): {array_1.min()}")
print(f"array_1.sum(): {array_1.sum()}")

array_1.std(): 2.8722813232690143
array_1.max(): 9
array_1.min(): 0
array_1.sum(): 45


Not all NumPy functions can be accessed this way:

In [11]:
print(f"array_1.median(): {array_1.median()}")

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [12]:
print(f"np.median(array_1): {np.median(array_1)}")

np.median(array_1): 4.5


In [14]:
print(f"array_1.std(): {array_1.std()}")
print(f"np.std(array_1): {np.std(array_1)}")

array_1.std(): 2.8722813232690143
np.std(array_1): 2.8722813232690143


![img/NumPy3.png](img/NumPy3.png)
![img/NumPy4.png](img/NumPy4.png)

Please, find a broader overview of _NumPy_ functions, e.g., on the [_Datacamp_](https://www.datacamp.com/community/data-science-cheatsheets) [_NumPy cheat sheet_](http://datacamp-community-prod.s3.amazonaws.com/da466534-51fe-4c6d-b0cb-154f4782eb54).

In [ ]:
# the find_nearest function (example):
import numpy as np

array_8 = np.array([0, 5, 5, 6, 6, 3, 9])

def find_nearest(input_array, search_number):
    """
    Simple function to search for the closest
    value within a given NumPy array.
    
    input_array: input array within we search
    search_number: integer or floating point 
                   number to search for in
                   input_array
    """
    array = np.asarray(input_array)
    idx = (np.abs(array - search_number)).argmin()
    return array[idx], idx

print(array_8)
print(find_nearest(array_8, 5.6))
""" 
Bear in mind, this function is not bullet-proof:
it doesn't return multiple occurrences of the found 
closest(s) value(s).
"""

## On array dimensionality

One very useful _NumPy_ command is `np.shape(array)` or `array.shape`, which returns the size and the shape (dimensions) of a given _array_:

In [15]:
print(f"array_1.shape(): {array_1.shape}")

array_1.shape(): (10,)


The output `(10,)` indicated, that `array_1` has only one axis, i.e. it is one-dimensional, with 10 entries on that axis. We can of course create NumPy arrays with higher dimensions:

In [16]:
# 2D array (e.g. an image), by input a list of tuples:
array_4 = np.array([(1, 2, 3),
                    (4, 5, 6),
                    (7, 8, 9), 
                    (7, 8, 9)]) 
print(f"array_4:")
print(array_4)
print(f"array_4.shape(): {array_4.shape}")

array_4:
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
array_4.shape(): (4, 3)


In [19]:
# What also works, is to input a list of list:
array_4 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9], 
                    [7, 8, 9]])
print(f"array_4:")
print(array_4)
print(f"array_4.shape(): {array_4.shape}")

array_4:
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
array_4.shape(): (4, 3)


In [10]:
# 3D array (e.g. an image stack):
array_5 = np.array([[(1,2,3), (4,5,6)], 
                    [(3,2,1), (4,5,6)]])
print(f"array_5:")
print(array_5)
print(f"array_5.shape(): {array_5.shape}")

>>>
array_5:
[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [4 5 6]]]
array_5.shape(): (2, 2, 3)


**Visual overview of NumPy array dimensionalities:**

<figure class="image">
  <img src="img/NumPy_dimensions.jpg" alt="NumPy array dimensions" style="width: 100%;">
  <figcaption>Multi-fluorescence image source: <a href="https://commons.wikimedia.org/wiki/File:MultiPhotonExcitation-Fig10-doi10.1186slash1475-925X-5-36-clipping.JPEG">commons.wikimedia.org</a>, license: <a href="https://creativecommons.org/licenses/by/2.0/deed.en">CC BY 2.0</a>; array dimension sketches taken from the <i><a href="https://www.datacamp.com/community/data-science-cheatsheets">Datacamp</a></i> <i><a href="http://datacamp-community-prod.s3.amazonaws.com/da466534-51fe-4c6d-b0cb-154f4782eb54">NumPy cheat sheet.</a></i></figcaption>
</figure>

## Useful helper functions for array generation
_NumPy_ brings some little helper functions to create n-dimensional arrays (sometimes helpful in prototyping and testing your programs or to understand a program):

In [20]:
# let NumPy create some arrays:
Z = np.zeros((3,4))
print(f"Z:")
print(Z)

Z:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
O = np.ones((3,4))
print(f"O:")
print(O)

O:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
print(O*7)

[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]


In [23]:
print(O+99)

[[100. 100. 100. 100.]
 [100. 100. 100. 100.]
 [100. 100. 100. 100.]]


In [55]:
L = np.linspace((1,21),
                (5,25),
                 5)
""" creates a 2D array; 1st column ranges from 1 (of (1,11)) 
    to 5 (of (5,15)), automatically spaced, so that we get
    5 (last number in the command) equally spaced increasing
    numbers. """
print(f"L:")
print(L)

L:
[[ 1. 21.]
 [ 2. 22.]
 [ 3. 23.]
 [ 4. 24.]
 [ 5. 25.]]


In [37]:
np.random.seed(1)
R = np.random.random((4,3))
# Creates some random numbers. The command np.random.seed(1)
#  fixes the machine internal random state for reproducibility.
print(f"R:")
print(R)

R:
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]
 [5.38816734e-01 4.19194514e-01 6.85219500e-01]]


## Indexing and slicing

Indexing and slicing of _NumPy_ arrays works similar as for lists:

In [41]:
print(f"shape of R: {R.shape} (4 rows, 3 columns)")

shape of R: (4, 3) (4 rows, 3 columns)


In [16]:
print(f"R[0,0]:")
print(R[0,0]) # Note, R is 2D and needs therefore two 
              #    index-values:
              #    first: row-index, second: column-index

>>>
R[0,0]:
0.417022004702574


In [39]:
print(R[1,0])

0.30233257263183977


In [40]:
print(f"R[:,0]:")
print(R[:,0])

R[:,0]:
[0.417022   0.30233257 0.18626021 0.53881673]


In [18]:
print(f"R[1:4,0]:")
print(R[1:4,0])

>>>
R[1:4,0]:
[0.30233257 0.18626021 0.53881673]


Also the output of the `shape` command is indexable: 

In [42]:
print(f"R.shape: {R.shape} (4 rows, 3 columns)")
print(f"R.shape[0]: {R.shape[0]} (4 rows)")
print(f"R.shape[1]: {R.shape[1]} (3 columns)")

R.shape: (4, 3) (4 rows, 3 columns)
R.shape[0]: 4 (4 rows)
R.shape[1]: 3 (3 columns)


## Exercise 1
Write a script, that defines the 2D _NumPy_ array `L` as defined above/as follows:

```python
L = np.linspace((1,11),
                (5,15),
                 5)
```

Iterate `L`

* over each row. Calculate and print the average of each row.
* over each column. Calculate and print the average of each column.

In [49]:
# Your solution 1 here:
L = np.linspace((1,11),
                (5,15),
                 5)
print(L)

# averages over rows...

# averages over columns...
print("")
print(L.mean(axis=0))
print(L.mean(axis=1))

[[ 1. 11.]
 [ 2. 12.]
 [ 3. 13.]
 [ 4. 14.]
 [ 5. 15.]]

[ 3. 13.]
[ 6.  7.  8.  9. 10.]


<details>
<summary><strong>Toggle solution</strong></summary>

```python
# Solution 1:
print(">>>")
print("L:")
print(L)

print("averages over rows:")
for row in range(L.shape[0]):
    print(L[row,:].mean())
    
print("averages over columns:")
for column in range(L.shape[1]):
    print(L[:,column].mean())
``` 
<script src="https://gist.github.com/username/a39a422ebdff6e732753b90573100b16.js"></script>
</details>

## Exercise 2
Given the _NumPy_ array `A`, that is defined as follows:
    
```python
A = np.array([np.arange(0,3,1)]*5,dtype='float16')
```

Write a script that
    
1. prints out its shape.
2. prints out all entries of column 1 and 2, separately and at once.
3. overwrites the values of column 1 by the sum of the values of  columns 2 and 3.
4. replaces the entry of row 1, column 3 with its exponentiation with the factor 2 (Hint: `x**2`).
5. replaces the entry of row 2, column 3 with the square root (`np.sqrt(value)`) of the entry of row 2, column 1.
6. prints out all entries with even index values of column 3.
7. calculates the average and standard deviation of all entries of column 3.

In [56]:
# Your solution 2.1 here:
A = np.array([np.arange(0,3,1)]*5,dtype='float16')
print(A)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


<details>
<summary><strong>Toggle solution</strong></summary>

```python
# Solution 2.1:
A = np.array([np.arange(0,3,1)]*5,dtype='float16')
print(">>>")
print("A:")
print(A)
print(f"A.shape: {A.shape}")
``` 
</details>

In [62]:
# Your solution 2.2 here:


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]
(5,)


<details>
<summary><strong>Toggle solution</strong></summary>

```python
# Solution 2.2:
print(">>>")
print(A[:, 0])
print(A[:, 1])
print(A[:, 0:2])
``` 
</details>

In [4]:
# Your solution 2.3 here:
print(">>>")
A[:,0] = A[:,1] + A[:,2]
print(A)

>>>
[[3. 1. 2.]
 [3. 1. 2.]
 [3. 1. 2.]
 [3. 1. 2.]
 [3. 1. 2.]]


<details>
<summary><strong>Toggle solution</strong></summary>

```python
# Solution 2.3:
print(">>>")
A[:,0] = A[:,1] + A[:,2]
print(A)
``` 
</details>

In [5]:
# Your solution 2.4 and 2.5 here:


>>>
4.0
1.732
[[3.    1.    4.   ]
 [3.    1.    1.732]
 [3.    1.    2.   ]
 [3.    1.    2.   ]
 [3.    1.    2.   ]]


<details>
<summary><strong>Toggle solution</strong></summary>

```python
# Solution 2.4 and 2.5:
print(">>>")
A[0,2] = A[0,2]**2
A[1,2] = np.sqrt(A[1,0])
print(A[0,2])
print(A[1,2])
print(A)
``` 
</details>

In [6]:
# Your solution 2.6 here:


>>>
[4. 2. 2.]


<details>
<summary><strong>Toggle solution</strong></summary>

```python
# Solution 2.6:
print(">>>")
print(A[0:5:2, 2]) # all entries with even index of column 3
``` 
</details>

In [7]:
# Your solution 2.7 here:


>>>
the result: 2.345703125 +/- 0.83349609375


<details>
<summary><strong>Toggle solution</strong></summary>

```python
# Solution 2.7:
print(">>>")
print(f"the result: {A[:,2].mean()} +/- {A[:,2].std()}")
``` 
</details>

In [17]:
# we can also round the numbers (unfortunateley, my
#  Jupyter Notebook produces some error here; in your
#  Spyder Editor it should work correctly)
#  e.g. round(2.65789, 2) means: round the 2.65789 to a 
#       number with 2 floating point numbers (here to: 2.66)
print(f"{np.round(A[:,2].mean(), 2)} +/- {np.round(A[:,2].std(),2)}")
print(round(A[:,2].mean(),2))
print(np.round(A[:,2].mean(),2))
print(f"{np.round(A[:,2].mean(),2)}")

2.349609375 +/- 0.830078125
2.35
2.35
2.349609375


## Exercise 3

1. Generate a _Numpy_ array `time` ranging from 0 to 5 in steps of 0.1.
2. Calculate the exponential values $y = e^{time}$ (Hint: `np.exp(array)`).
3. Copy your created `y` into another variable called, e.g.,  `y_noisy`.
4. Add some noise to `y_noisy` by adding `np.random.randn(len(time))*10`.
5. Import the Gaussian 1D filter function from the _scipy ndimage_ package: 
    ```python
       from scipy.ndimage import gaussian_filter1d
    ```
    
    If the `scipy` module is missing, please install it. Please inform yourself about this function on [docs.scipy.org](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_filter1d.html).
6. Apply the Gaussian filter to the noisy signal (`gaussian_filter1d(y_noisy, sigma)`) 
    1. with `sigma = 3`
    2. with `sigma = 6`

  (again, save your results into new variables, e.g., `y_denoised_3` and `y_denoised_6`)

In [64]:
# Your solution 3 here:
import numpy as np
from scipy.ndimage import gaussian_filter1d

# create data arrays:
time = np.arange(0,5, 0.1)
y = np.exp(time)

# add some noise:
y_noisy = y.copy()
y_noisy = y_noisy  + np.random.randn(len(time))*10

# apply filters:
y_denoised_3 = gaussian_filter1d(y_noisy, 3)
y_denoised_6 = gaussian_filter1d(y_noisy, 6)

<details>
<summary><strong>Toggle solution</strong></summary>

```python
# Solution 3:
import numpy as np
from scipy.ndimage import gaussian_filter1d

# create data arrays:
time = np.arange(0,5, 0.1)
y = np.exp(time)

# add some noise:
y_noisy = y.copy()
y_noisy = y_noisy  + np.random.randn(len(time))*10

# apply filters:
y_denoised_3 = gaussian_filter1d(y_noisy, 3)
y_denoised_6 = gaussian_filter1d(y_noisy, 6)
``` 
</details>

## Shallow vs. Deep Copy

Also for _NumPy_ arrays account the shallow and deep copy rules:

In [35]:
# shallow copy only:
array_1 = np.arange(0,3,1)  # create the first array_1
array_2 = array_1           # create another array by
                            # shallow copying array_1

print("array_2 after shallow copying array_1:")
print("array_1:", array_1, "array_2:", array_2) 

>>>
array_2 after shallow copying array_1:
array_1: [0 1 2] array_2: [0 1 2]


In [36]:
# modify the shallow copy:
array_2[1] = -7

print("array_2 modified after shallow copying array_1:")
print('array_1:', array_1, 'array_2:', array_2)

>>>
array_2 modified after shallow copying array_1:
array_1: [ 0 -7  2] array_2: [ 0 -7  2]


Note, that also `array_1` has been modified, too!

In [37]:
# deep copy:
array_2 = array_1.copy()  # deep copy in NumPy
array_2[1] = 20

print("array_2 modified after deep copying array_1:")
print('array_1:', array_1, 'array_2:', array_2)

>>>
array_2 modified after deep copying array_1:
array_1: [ 0 -7  2] array_2: [ 0 20  2]


A deep copy with _NumPy_ can be achieved via the following commands:

- `array.copy()`
- `np.copy(array)`